# Generated by Django 5.0.7 on 2024-09-13 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_educationnelle', models.CharField(max_length=255)),
                ('ecole', models.CharField(max_length=255)),
                ('annee_obtention_diplome', models.IntegerField()),
                ('option', models.CharField(blank=True, max_length=255, null=True)),
                ('nom', models.CharField(max_length=255)),
                ('post_nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('etat_civil', models.CharField(max_length=50)),
                ('pourcentage', models.CharField(max_length=10)),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=255)),
                ('province_origine', models.CharField(max_length=255)),
                ('territoire_district', models.CharField(max_length=255)),
                ('secteur', models.CharField(max_length=255)),
                ('adresse_mail', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('adresse_complet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.faculte')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='S1', max_length=255)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Choix_filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.departement')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.etudiant')),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.faculte')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiant.promotion')),
            ],
        ),
    ]
