# Generated by Django 5.0.7 on 2024-09-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='etat_civil',
            field=models.CharField(choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='province_origine',
            field=models.CharField(choices=[('KINSHASA', 'Kinshasa'), ('BAS_UELE', 'Bas-Uele'), ('HAUT_UELE', 'Haut-Uele'), ('ITURI', 'Ituri'), ('NORD_KIVU', 'Nord-Kivu'), ('SUD_KIVU', 'Sud-Kivu'), ('MANIEMA', 'Maniema'), ('HAUT_LOMAMI', 'Haut-Lomami'), ('TANGANYIKA', 'Tanganyika'), ('LOMAMI', 'Lomami'), ('KASAI', 'Kasaï'), ('KASAI_CENTRAL', 'Kasaï-Central'), ('KASAI_ORIENTAL', 'Kasaï-Oriental'), ('HAUT_KATANGA', 'Haut-Katanga'), ('LUALABA', 'Lualaba'), ('EQUATEUR', 'Équateur'), ('SUD_UBANGI', 'Sud-Ubangi'), ('NORD_UBANGI', 'Nord-Ubangi'), ('MONGALA', 'Mongala'), ('TSHOPO', 'Tshopo'), ('TSHUAPA', 'Tshuapa'), ('MAI_NDOMBE', 'Mai-Ndombe'), ('KWILU', 'Kwilu'), ('KWANGO', 'Kwango'), ('KINSHASA', 'Kinshasa')], max_length=255),
        ),
    ]
